In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from textblob import TextBlob
import spacy

In [57]:
df = pd.read_csv("amazon.csv")

In [58]:
df["rating"] = pd.to_numeric(df['rating'], errors='coerce')
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [59]:
df = df[df["rating"].isna() == False]

In [56]:
def polaridad(rating):
    if(rating > 4.2): return 1
    elif(rating > 2.5): return 0
    else: return -1

In [60]:
#Conversion a review positiva, neutral o negativa

df["polarity"] = df.apply(lambda a: polaridad(a["rating"]), axis=1)

In [113]:
df["polarity"].value_counts()

polarity
 0    1005
 1     457
-1       2
Name: count, dtype: int64

In [183]:
neutro = pd.DataFrame(columns=["review_content", "polarity"])
neutro["review_content"] = df["review_content"].head(1000)
neutro["polarity"] = df["polarity"].head(1000)
neutro.head()

                                      review_content  polarity
0  Looks durable Charging is fine tooNo complains...         0
1  I ordered this cable to connect my phone to An...         0
2  Not quite durable and sturdy,https://m.media-a...         0
3  Good product,long wire,Charges good,Nice,I bou...         0
4  Bought this instead of original apple, does th...         0

In [184]:
nuevo = pd.read_csv("train_lite.csv", names=["polarity", "rev_title", "review_content"])
nuevo = nuevo[["polarity", "review_content"]]
nuevo.head()

   polarity                                     review_content
0         1  I have tried so many times to get this thing t...
1         1  My baby did NOT like this sling at all. I have...
2         1  All I have to say is who is going put together...
3         1  My chair was received without all of the parts...
4         1  Extremely disappointed that a company as well ...

In [ ]:
df2 = pd.DataFrame(columns=["review_content", "polarity"])
d1 = nuevo[nuevo["polarity"] == 1].head(1000) # negativos
d2 = nuevo[nuevo["polarity"] == 2].head(1000) # positivos
df2.reset_index()
df2 = pd.concat([neutro, d1], ignore_index=False)

In [175]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_content  2000 non-null   object
 1   polarity        2000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 31.4+ KB

In [176]:
df2["polarity"].value_counts()

polarity
1    1349
0     651
Name: count, dtype: int64

In [163]:
df2.head()

                                      review_content  polarity
0  Looks durable Charging is fine tooNo complains...         0
1  I ordered this cable to connect my phone to An...         0
2  Not quite durable and sturdy,https://m.media-a...         0
3  Good product,long wire,Charges good,Nice,I bou...         0
4  Bought this instead of original apple, does th...         0

In [182]:
df2.loc[988:1000]

                                         review_content  polarity
988   As per expectations,At this price point, guide...         0
989   Good product,Stability: okSturdiness: mediumMa...         0
990   Product is good , and also it's  strudiness .B...         0
991   After 1 month of use  i can say that this is b...         1
992   Everything is fine but it is bulky and hard, i...         0
993   Bahut aacha hai ye pen sach me likhne ke Baad ...         0
994   Its really good,Best stand from others in pric...         1
995   Keyboard is good. I don't really like that cli...         1
996   it's quality is really good and it can carry 1...         0
997   very good product, very bright, easy to use, i...         0
998   No complaints till now. Only cons is 1st time ...         0
999   The LED light is vibrant with multiple form se...         0
1000  I have tried so many times to get this thing t...         1